openapi: "3.0.0"
info:
  title: Simple API overview
  version: 2.0.0
tags:
  - name: Person
paths:
  /multimodule-hexagonal/person:
    get:
      operationId: personInfo
      summary: List API versions
      tags:
        - Person
      responses:
        '200':
          $ref: '#/components/responses/Person200'

components:
  schemas:
    Person:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Luis
      required:
        - id
        - name
      additionalProperties: false

  responses:
    Person200:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Person'
