services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=test'
    ports:
      - 27017:27017
    volumes:
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
    restart: always