spring:
  data:
    mongodb:
      user: test
      password: test
      uri: mongodb://localhost:27017/test
      uuid-representation: standard
      auto-index-creation: true
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
server:
  servlet:
    context-path: /pruebas